//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9145
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.9145.
// 
#pragma warning disable 1591

namespace webservice.WebReference {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9136")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService_kanbanSoap", Namespace="http://tempuri.org/")]
    public partial class WebService_kanban : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback insert_data_to_db_from_localOperationCompleted;
        
        private System.Threading.SendOrPostCallback updatate_dataOperationCompleted;
        
        private System.Threading.SendOrPostCallback count_rows_dbOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_m_kanbanOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_part_tagOperationCompleted;
        
        private System.Threading.SendOrPostCallback loginOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService_kanban() {
            this.Url = global::webservice.Properties.Settings.Default.webservice_WebReference_WebService_kanban;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event insert_data_to_db_from_localCompletedEventHandler insert_data_to_db_from_localCompleted;
        
        /// <remarks/>
        public event updatate_dataCompletedEventHandler updatate_dataCompleted;
        
        /// <remarks/>
        public event count_rows_dbCompletedEventHandler count_rows_dbCompleted;
        
        /// <remarks/>
        public event get_m_kanbanCompletedEventHandler get_m_kanbanCompleted;
        
        /// <remarks/>
        public event get_part_tagCompletedEventHandler get_part_tagCompleted;
        
        /// <remarks/>
        public event loginCompletedEventHandler loginCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insert_data_to_db_from_local", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable insert_data_to_db_from_local(string partnumber, string srctcode, string dockcode, int pack, string error, string chk, string user, System.DateTime day, string ekb, string kbid) {
            object[] results = this.Invoke("insert_data_to_db_from_local", new object[] {
                        partnumber,
                        srctcode,
                        dockcode,
                        pack,
                        error,
                        chk,
                        user,
                        day,
                        ekb,
                        kbid});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void insert_data_to_db_from_localAsync(string partnumber, string srctcode, string dockcode, int pack, string error, string chk, string user, System.DateTime day, string ekb, string kbid) {
            this.insert_data_to_db_from_localAsync(partnumber, srctcode, dockcode, pack, error, chk, user, day, ekb, kbid, null);
        }
        
        /// <remarks/>
        public void insert_data_to_db_from_localAsync(string partnumber, string srctcode, string dockcode, int pack, string error, string chk, string user, System.DateTime day, string ekb, string kbid, object userState) {
            if ((this.insert_data_to_db_from_localOperationCompleted == null)) {
                this.insert_data_to_db_from_localOperationCompleted = new System.Threading.SendOrPostCallback(this.Oninsert_data_to_db_from_localOperationCompleted);
            }
            this.InvokeAsync("insert_data_to_db_from_local", new object[] {
                        partnumber,
                        srctcode,
                        dockcode,
                        pack,
                        error,
                        chk,
                        user,
                        day,
                        ekb,
                        kbid}, this.insert_data_to_db_from_localOperationCompleted, userState);
        }
        
        private void Oninsert_data_to_db_from_localOperationCompleted(object arg) {
            if ((this.insert_data_to_db_from_localCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insert_data_to_db_from_localCompleted(this, new insert_data_to_db_from_localCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updatate_data", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable updatate_data(string Partnumber, string Srctcode, string dockcode, int qty, string error, string type, bool bit, string user, System.DateTime day, string pds, string order, string kbid) {
            object[] results = this.Invoke("updatate_data", new object[] {
                        Partnumber,
                        Srctcode,
                        dockcode,
                        qty,
                        error,
                        type,
                        bit,
                        user,
                        day,
                        pds,
                        order,
                        kbid});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void updatate_dataAsync(string Partnumber, string Srctcode, string dockcode, int qty, string error, string type, bool bit, string user, System.DateTime day, string pds, string order, string kbid) {
            this.updatate_dataAsync(Partnumber, Srctcode, dockcode, qty, error, type, bit, user, day, pds, order, kbid, null);
        }
        
        /// <remarks/>
        public void updatate_dataAsync(string Partnumber, string Srctcode, string dockcode, int qty, string error, string type, bool bit, string user, System.DateTime day, string pds, string order, string kbid, object userState) {
            if ((this.updatate_dataOperationCompleted == null)) {
                this.updatate_dataOperationCompleted = new System.Threading.SendOrPostCallback(this.Onupdatate_dataOperationCompleted);
            }
            this.InvokeAsync("updatate_data", new object[] {
                        Partnumber,
                        Srctcode,
                        dockcode,
                        qty,
                        error,
                        type,
                        bit,
                        user,
                        day,
                        pds,
                        order,
                        kbid}, this.updatate_dataOperationCompleted, userState);
        }
        
        private void Onupdatate_dataOperationCompleted(object arg) {
            if ((this.updatate_dataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updatate_dataCompleted(this, new updatate_dataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/count_rows_db", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable count_rows_db() {
            object[] results = this.Invoke("count_rows_db", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void count_rows_dbAsync() {
            this.count_rows_dbAsync(null);
        }
        
        /// <remarks/>
        public void count_rows_dbAsync(object userState) {
            if ((this.count_rows_dbOperationCompleted == null)) {
                this.count_rows_dbOperationCompleted = new System.Threading.SendOrPostCallback(this.Oncount_rows_dbOperationCompleted);
            }
            this.InvokeAsync("count_rows_db", new object[0], this.count_rows_dbOperationCompleted, userState);
        }
        
        private void Oncount_rows_dbOperationCompleted(object arg) {
            if ((this.count_rows_dbCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.count_rows_dbCompleted(this, new count_rows_dbCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_m_kanban", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable get_m_kanban() {
            object[] results = this.Invoke("get_m_kanban", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void get_m_kanbanAsync() {
            this.get_m_kanbanAsync(null);
        }
        
        /// <remarks/>
        public void get_m_kanbanAsync(object userState) {
            if ((this.get_m_kanbanOperationCompleted == null)) {
                this.get_m_kanbanOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_m_kanbanOperationCompleted);
            }
            this.InvokeAsync("get_m_kanban", new object[0], this.get_m_kanbanOperationCompleted, userState);
        }
        
        private void Onget_m_kanbanOperationCompleted(object arg) {
            if ((this.get_m_kanbanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_m_kanbanCompleted(this, new get_m_kanbanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_part_tag", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable get_part_tag(string delivery) {
            object[] results = this.Invoke("get_part_tag", new object[] {
                        delivery});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void get_part_tagAsync(string delivery) {
            this.get_part_tagAsync(delivery, null);
        }
        
        /// <remarks/>
        public void get_part_tagAsync(string delivery, object userState) {
            if ((this.get_part_tagOperationCompleted == null)) {
                this.get_part_tagOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_part_tagOperationCompleted);
            }
            this.InvokeAsync("get_part_tag", new object[] {
                        delivery}, this.get_part_tagOperationCompleted, userState);
        }
        
        private void Onget_part_tagOperationCompleted(object arg) {
            if ((this.get_part_tagCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_part_tagCompleted(this, new get_part_tagCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable login(string username) {
            object[] results = this.Invoke("login", new object[] {
                        username});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void loginAsync(string username) {
            this.loginAsync(username, null);
        }
        
        /// <remarks/>
        public void loginAsync(string username, object userState) {
            if ((this.loginOperationCompleted == null)) {
                this.loginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginOperationCompleted);
            }
            this.InvokeAsync("login", new object[] {
                        username}, this.loginOperationCompleted, userState);
        }
        
        private void OnloginOperationCompleted(object arg) {
            if ((this.loginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginCompleted(this, new loginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9136")]
    public delegate void insert_data_to_db_from_localCompletedEventHandler(object sender, insert_data_to_db_from_localCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9136")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insert_data_to_db_from_localCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insert_data_to_db_from_localCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9136")]
    public delegate void updatate_dataCompletedEventHandler(object sender, updatate_dataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9136")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updatate_dataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updatate_dataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9136")]
    public delegate void count_rows_dbCompletedEventHandler(object sender, count_rows_dbCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9136")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class count_rows_dbCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal count_rows_dbCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9136")]
    public delegate void get_m_kanbanCompletedEventHandler(object sender, get_m_kanbanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9136")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_m_kanbanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_m_kanbanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9136")]
    public delegate void get_part_tagCompletedEventHandler(object sender, get_part_tagCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9136")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_part_tagCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_part_tagCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9136")]
    public delegate void loginCompletedEventHandler(object sender, loginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9136")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591